### PR TITLE
Drop PostgreSQL 10

### PR DESCRIPTION
**Pull request by komainu8**
Because PGroonga already dropped support for PostgreSQL 10.

### CODE REVIEW

**Comment by kou** [comment]
Could you also remove invalid entries in README.md?
For example, `2.4.2-alpine-10-slim` entry is invalid.

**Comment by komainu8** [comment]
> Could you also remove invalid entries in README.md?
> For example, 2.4.2-alpine-10-slim entry is invalid.

I see.
I removed them.

**Comment by kou** [comment]
2.4.1 based images are also invalid because PGroonga 2.4.1 dropped support PostgreSQL 10.

**Comment by komainu8** [comment]
Oh...Sorry.

**Comment by komainu8** [comment]
I've removed them.

**Pull request merged**
