### PR TITLE
Add support for PostgreSQL 16

### PR DESCRIPTION
**Pull request by komainu8**
GitHub: fix GH-34

Reported by Geosite Development Team. Thanks!!!

### CODE REVIEW

**Comment by kou** [comment]
We want to update https://github.com/pgroonga/docker#supported-tags-and-respective-dockerfile-links too.

**Comment by komainu8** [comment]
Docker image build success.

https://github.com/pgroonga/docker/actions/runs/6401775670 failed. However, the cause of this fail that PGroonga Docker image with PostgreSQL 16 upload to Docker Hub yet.

**Comment by kou** [comment]
We need to re-tag 3.1.5.

**Comment by komainu8** [comment]
I finished re-tag 3.1.5.

**Pull request merged**
